### ISSUE TITLE
Make GitLab host configurable

### ISSUE THREAD

**Issue by vbrandl** [zupzup/gitlab-push-and-mr#2]
It would be cool to be able to configure another GitLab host, so this tool could be used with selfhosted GitLab instances.

**Comment by zupzup** [comment]
That's a great suggestion, thx @vbrandl 

Do you know how versioning / API access differs between the cloud version and self-hosted Gitlab instances?

I only have experience with the cloud version unfortunately.

**Comment by vbrandl** [comment]
The APIs are compatible (except some endpoints that are only available in gitlab-ee but not in gitlab-ce).

It should be enough to add a new field to your config (`hostname`) and use the serde `default` attribute (https://serde.rs/field-attrs.html).

Something like this should work

```rust
fn default_host() -> String {
  "https://gitlab.com/".to_string()
}
struct Config {
  ...
  #[serde(default = "default_host")] 
  hostname: String
}
```
